// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errorDefinition.proto

package com.errclipse.rmi.interfaces;

public final class GGeneralErrorClazz {
  private GGeneralErrorClazz() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ErrorQueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string language_name = 1;
    boolean hasLanguageName();
    String getLanguageName();
    
    // required string library_name = 2;
    boolean hasLibraryName();
    String getLibraryName();
    
    // required string method_name = 3;
    boolean hasMethodName();
    String getMethodName();
    
    // required string error_name = 4;
    boolean hasErrorName();
    String getErrorName();
  }
  public static final class ErrorQuery extends
      com.google.protobuf.GeneratedMessage
      implements ErrorQueryOrBuilder {
    // Use ErrorQuery.newBuilder() to construct.
    private ErrorQuery(Builder builder) {
      super(builder);
    }
    private ErrorQuery(boolean noInit) {}
    
    private static final ErrorQuery defaultInstance;
    public static ErrorQuery getDefaultInstance() {
      return defaultInstance;
    }
    
    public ErrorQuery getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_ErrorQuery_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_ErrorQuery_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string language_name = 1;
    public static final int LANGUAGE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object languageName_;
    public boolean hasLanguageName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLanguageName() {
      java.lang.Object ref = languageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          languageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLanguageNameBytes() {
      java.lang.Object ref = languageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        languageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string library_name = 2;
    public static final int LIBRARY_NAME_FIELD_NUMBER = 2;
    private java.lang.Object libraryName_;
    public boolean hasLibraryName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLibraryName() {
      java.lang.Object ref = libraryName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          libraryName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLibraryNameBytes() {
      java.lang.Object ref = libraryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        libraryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string method_name = 3;
    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    private java.lang.Object methodName_;
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string error_name = 4;
    public static final int ERROR_NAME_FIELD_NUMBER = 4;
    private java.lang.Object errorName_;
    public boolean hasErrorName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getErrorName() {
      java.lang.Object ref = errorName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorNameBytes() {
      java.lang.Object ref = errorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      languageName_ = "";
      libraryName_ = "";
      methodName_ = "";
      errorName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLanguageName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLibraryName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLanguageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLibraryNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getErrorNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLanguageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLibraryNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getErrorNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_ErrorQuery_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_ErrorQuery_fieldAccessorTable;
      }
      
      // Construct using com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        languageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        libraryName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        errorName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery.getDescriptor();
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery getDefaultInstanceForType() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery.getDefaultInstance();
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery build() {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery buildPartial() {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery result = new com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.languageName_ = languageName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.libraryName_ = libraryName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorName_ = errorName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery) {
          return mergeFrom((com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery other) {
        if (other == com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery.getDefaultInstance()) return this;
        if (other.hasLanguageName()) {
          setLanguageName(other.getLanguageName());
        }
        if (other.hasLibraryName()) {
          setLibraryName(other.getLibraryName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasErrorName()) {
          setErrorName(other.getErrorName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLanguageName()) {
          
          return false;
        }
        if (!hasLibraryName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        if (!hasErrorName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              languageName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              libraryName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              methodName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              errorName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string language_name = 1;
      private java.lang.Object languageName_ = "";
      public boolean hasLanguageName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLanguageName() {
        java.lang.Object ref = languageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          languageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLanguageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        languageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLanguageName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        languageName_ = getDefaultInstance().getLanguageName();
        onChanged();
        return this;
      }
      void setLanguageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        languageName_ = value;
        onChanged();
      }
      
      // required string library_name = 2;
      private java.lang.Object libraryName_ = "";
      public boolean hasLibraryName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLibraryName() {
        java.lang.Object ref = libraryName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          libraryName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLibraryName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        libraryName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLibraryName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        libraryName_ = getDefaultInstance().getLibraryName();
        onChanged();
        return this;
      }
      void setLibraryName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        libraryName_ = value;
        onChanged();
      }
      
      // required string method_name = 3;
      private java.lang.Object methodName_ = "";
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      void setMethodName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
      }
      
      // required string error_name = 4;
      private java.lang.Object errorName_ = "";
      public boolean hasErrorName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getErrorName() {
        java.lang.Object ref = errorName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorName_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorName_ = getDefaultInstance().getErrorName();
        onChanged();
        return this;
      }
      void setErrorName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        errorName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.errclipse.rmi.interfaces.ErrorQuery)
    }
    
    static {
      defaultInstance = new ErrorQuery(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.errclipse.rmi.interfaces.ErrorQuery)
  }
  
  public interface SolutionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string decs = 1;
    boolean hasDecs();
    String getDecs();
    
    // required int32 local_score = 2;
    boolean hasLocalScore();
    int getLocalScore();
    
    // required float global_score = 3;
    boolean hasGlobalScore();
    float getGlobalScore();
  }
  public static final class Solution extends
      com.google.protobuf.GeneratedMessage
      implements SolutionOrBuilder {
    // Use Solution.newBuilder() to construct.
    private Solution(Builder builder) {
      super(builder);
    }
    private Solution(boolean noInit) {}
    
    private static final Solution defaultInstance;
    public static Solution getDefaultInstance() {
      return defaultInstance;
    }
    
    public Solution getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_Solution_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_Solution_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string decs = 1;
    public static final int DECS_FIELD_NUMBER = 1;
    private java.lang.Object decs_;
    public boolean hasDecs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDecs() {
      java.lang.Object ref = decs_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          decs_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDecsBytes() {
      java.lang.Object ref = decs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        decs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 local_score = 2;
    public static final int LOCAL_SCORE_FIELD_NUMBER = 2;
    private int localScore_;
    public boolean hasLocalScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLocalScore() {
      return localScore_;
    }
    
    // required float global_score = 3;
    public static final int GLOBAL_SCORE_FIELD_NUMBER = 3;
    private float globalScore_;
    public boolean hasGlobalScore() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getGlobalScore() {
      return globalScore_;
    }
    
    private void initFields() {
      decs_ = "";
      localScore_ = 0;
      globalScore_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDecs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGlobalScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDecsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, localScore_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, globalScore_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDecsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, localScore_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, globalScore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_Solution_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_Solution_fieldAccessorTable;
      }
      
      // Construct using com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        decs_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        localScore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        globalScore_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.getDescriptor();
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution getDefaultInstanceForType() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.getDefaultInstance();
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution build() {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution buildPartial() {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution result = new com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.decs_ = decs_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localScore_ = localScore_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.globalScore_ = globalScore_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution) {
          return mergeFrom((com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution other) {
        if (other == com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.getDefaultInstance()) return this;
        if (other.hasDecs()) {
          setDecs(other.getDecs());
        }
        if (other.hasLocalScore()) {
          setLocalScore(other.getLocalScore());
        }
        if (other.hasGlobalScore()) {
          setGlobalScore(other.getGlobalScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDecs()) {
          
          return false;
        }
        if (!hasLocalScore()) {
          
          return false;
        }
        if (!hasGlobalScore()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              decs_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              localScore_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              globalScore_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string decs = 1;
      private java.lang.Object decs_ = "";
      public boolean hasDecs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDecs() {
        java.lang.Object ref = decs_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          decs_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDecs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        decs_ = value;
        onChanged();
        return this;
      }
      public Builder clearDecs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        decs_ = getDefaultInstance().getDecs();
        onChanged();
        return this;
      }
      void setDecs(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        decs_ = value;
        onChanged();
      }
      
      // required int32 local_score = 2;
      private int localScore_ ;
      public boolean hasLocalScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLocalScore() {
        return localScore_;
      }
      public Builder setLocalScore(int value) {
        bitField0_ |= 0x00000002;
        localScore_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocalScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localScore_ = 0;
        onChanged();
        return this;
      }
      
      // required float global_score = 3;
      private float globalScore_ ;
      public boolean hasGlobalScore() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getGlobalScore() {
        return globalScore_;
      }
      public Builder setGlobalScore(float value) {
        bitField0_ |= 0x00000004;
        globalScore_ = value;
        onChanged();
        return this;
      }
      public Builder clearGlobalScore() {
        bitField0_ = (bitField0_ & ~0x00000004);
        globalScore_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.errclipse.rmi.interfaces.Solution)
    }
    
    static {
      defaultInstance = new Solution(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.errclipse.rmi.interfaces.Solution)
  }
  
  public interface SolutionResultListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool is_solution_find = 1;
    boolean hasIsSolutionFind();
    boolean getIsSolutionFind();
    
    // repeated .com.errclipse.rmi.interfaces.Solution solution_list = 2;
    java.util.List<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution> 
        getSolutionListList();
    com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution getSolutionList(int index);
    int getSolutionListCount();
    java.util.List<? extends com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder> 
        getSolutionListOrBuilderList();
    com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder getSolutionListOrBuilder(
        int index);
  }
  public static final class SolutionResultList extends
      com.google.protobuf.GeneratedMessage
      implements SolutionResultListOrBuilder {
    // Use SolutionResultList.newBuilder() to construct.
    private SolutionResultList(Builder builder) {
      super(builder);
    }
    private SolutionResultList(boolean noInit) {}
    
    private static final SolutionResultList defaultInstance;
    public static SolutionResultList getDefaultInstance() {
      return defaultInstance;
    }
    
    public SolutionResultList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_SolutionResultList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_SolutionResultList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool is_solution_find = 1;
    public static final int IS_SOLUTION_FIND_FIELD_NUMBER = 1;
    private boolean isSolutionFind_;
    public boolean hasIsSolutionFind() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getIsSolutionFind() {
      return isSolutionFind_;
    }
    
    // repeated .com.errclipse.rmi.interfaces.Solution solution_list = 2;
    public static final int SOLUTION_LIST_FIELD_NUMBER = 2;
    private java.util.List<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution> solutionList_;
    public java.util.List<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution> getSolutionListList() {
      return solutionList_;
    }
    public java.util.List<? extends com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder> 
        getSolutionListOrBuilderList() {
      return solutionList_;
    }
    public int getSolutionListCount() {
      return solutionList_.size();
    }
    public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution getSolutionList(int index) {
      return solutionList_.get(index);
    }
    public com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder getSolutionListOrBuilder(
        int index) {
      return solutionList_.get(index);
    }
    
    private void initFields() {
      isSolutionFind_ = false;
      solutionList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasIsSolutionFind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSolutionListCount(); i++) {
        if (!getSolutionList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSolutionFind_);
      }
      for (int i = 0; i < solutionList_.size(); i++) {
        output.writeMessage(2, solutionList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSolutionFind_);
      }
      for (int i = 0; i < solutionList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, solutionList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_SolutionResultList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.internal_static_com_errclipse_rmi_interfaces_SolutionResultList_fieldAccessorTable;
      }
      
      // Construct using com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSolutionListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        isSolutionFind_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (solutionListBuilder_ == null) {
          solutionList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          solutionListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList.getDescriptor();
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList getDefaultInstanceForType() {
        return com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList.getDefaultInstance();
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList build() {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList buildPartial() {
        com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList result = new com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSolutionFind_ = isSolutionFind_;
        if (solutionListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            solutionList_ = java.util.Collections.unmodifiableList(solutionList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.solutionList_ = solutionList_;
        } else {
          result.solutionList_ = solutionListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList) {
          return mergeFrom((com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList other) {
        if (other == com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList.getDefaultInstance()) return this;
        if (other.hasIsSolutionFind()) {
          setIsSolutionFind(other.getIsSolutionFind());
        }
        if (solutionListBuilder_ == null) {
          if (!other.solutionList_.isEmpty()) {
            if (solutionList_.isEmpty()) {
              solutionList_ = other.solutionList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSolutionListIsMutable();
              solutionList_.addAll(other.solutionList_);
            }
            onChanged();
          }
        } else {
          if (!other.solutionList_.isEmpty()) {
            if (solutionListBuilder_.isEmpty()) {
              solutionListBuilder_.dispose();
              solutionListBuilder_ = null;
              solutionList_ = other.solutionList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              solutionListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSolutionListFieldBuilder() : null;
            } else {
              solutionListBuilder_.addAllMessages(other.solutionList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasIsSolutionFind()) {
          
          return false;
        }
        for (int i = 0; i < getSolutionListCount(); i++) {
          if (!getSolutionList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSolutionFind_ = input.readBool();
              break;
            }
            case 18: {
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder subBuilder = com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSolutionList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool is_solution_find = 1;
      private boolean isSolutionFind_ ;
      public boolean hasIsSolutionFind() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getIsSolutionFind() {
        return isSolutionFind_;
      }
      public Builder setIsSolutionFind(boolean value) {
        bitField0_ |= 0x00000001;
        isSolutionFind_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsSolutionFind() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSolutionFind_ = false;
        onChanged();
        return this;
      }
      
      // repeated .com.errclipse.rmi.interfaces.Solution solution_list = 2;
      private java.util.List<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution> solutionList_ =
        java.util.Collections.emptyList();
      private void ensureSolutionListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          solutionList_ = new java.util.ArrayList<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution>(solutionList_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder, com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder> solutionListBuilder_;
      
      public java.util.List<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution> getSolutionListList() {
        if (solutionListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(solutionList_);
        } else {
          return solutionListBuilder_.getMessageList();
        }
      }
      public int getSolutionListCount() {
        if (solutionListBuilder_ == null) {
          return solutionList_.size();
        } else {
          return solutionListBuilder_.getCount();
        }
      }
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution getSolutionList(int index) {
        if (solutionListBuilder_ == null) {
          return solutionList_.get(index);
        } else {
          return solutionListBuilder_.getMessage(index);
        }
      }
      public Builder setSolutionList(
          int index, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution value) {
        if (solutionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSolutionListIsMutable();
          solutionList_.set(index, value);
          onChanged();
        } else {
          solutionListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSolutionList(
          int index, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder builderForValue) {
        if (solutionListBuilder_ == null) {
          ensureSolutionListIsMutable();
          solutionList_.set(index, builderForValue.build());
          onChanged();
        } else {
          solutionListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSolutionList(com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution value) {
        if (solutionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSolutionListIsMutable();
          solutionList_.add(value);
          onChanged();
        } else {
          solutionListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSolutionList(
          int index, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution value) {
        if (solutionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSolutionListIsMutable();
          solutionList_.add(index, value);
          onChanged();
        } else {
          solutionListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSolutionList(
          com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder builderForValue) {
        if (solutionListBuilder_ == null) {
          ensureSolutionListIsMutable();
          solutionList_.add(builderForValue.build());
          onChanged();
        } else {
          solutionListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSolutionList(
          int index, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder builderForValue) {
        if (solutionListBuilder_ == null) {
          ensureSolutionListIsMutable();
          solutionList_.add(index, builderForValue.build());
          onChanged();
        } else {
          solutionListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSolutionList(
          java.lang.Iterable<? extends com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution> values) {
        if (solutionListBuilder_ == null) {
          ensureSolutionListIsMutable();
          super.addAll(values, solutionList_);
          onChanged();
        } else {
          solutionListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSolutionList() {
        if (solutionListBuilder_ == null) {
          solutionList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          solutionListBuilder_.clear();
        }
        return this;
      }
      public Builder removeSolutionList(int index) {
        if (solutionListBuilder_ == null) {
          ensureSolutionListIsMutable();
          solutionList_.remove(index);
          onChanged();
        } else {
          solutionListBuilder_.remove(index);
        }
        return this;
      }
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder getSolutionListBuilder(
          int index) {
        return getSolutionListFieldBuilder().getBuilder(index);
      }
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder getSolutionListOrBuilder(
          int index) {
        if (solutionListBuilder_ == null) {
          return solutionList_.get(index);  } else {
          return solutionListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder> 
           getSolutionListOrBuilderList() {
        if (solutionListBuilder_ != null) {
          return solutionListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(solutionList_);
        }
      }
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder addSolutionListBuilder() {
        return getSolutionListFieldBuilder().addBuilder(
            com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.getDefaultInstance());
      }
      public com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder addSolutionListBuilder(
          int index) {
        return getSolutionListFieldBuilder().addBuilder(
            index, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.getDefaultInstance());
      }
      public java.util.List<com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder> 
           getSolutionListBuilderList() {
        return getSolutionListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder, com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder> 
          getSolutionListFieldBuilder() {
        if (solutionListBuilder_ == null) {
          solutionListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution, com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder, com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionOrBuilder>(
                  solutionList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          solutionList_ = null;
        }
        return solutionListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.errclipse.rmi.interfaces.SolutionResultList)
    }
    
    static {
      defaultInstance = new SolutionResultList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.errclipse.rmi.interfaces.SolutionResultList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_errclipse_rmi_interfaces_ErrorQuery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_errclipse_rmi_interfaces_ErrorQuery_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_errclipse_rmi_interfaces_Solution_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_errclipse_rmi_interfaces_Solution_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_errclipse_rmi_interfaces_SolutionResultList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_errclipse_rmi_interfaces_SolutionResultList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025errorDefinition.proto\022\034com.errclipse.r" +
      "mi.interfaces\"b\n\nErrorQuery\022\025\n\rlanguage_" +
      "name\030\001 \002(\t\022\024\n\014library_name\030\002 \002(\t\022\023\n\013meth" +
      "od_name\030\003 \002(\t\022\022\n\nerror_name\030\004 \002(\t\"C\n\010Sol" +
      "ution\022\014\n\004decs\030\001 \002(\t\022\023\n\013local_score\030\002 \002(\005" +
      "\022\024\n\014global_score\030\003 \002(\002\"m\n\022SolutionResult" +
      "List\022\030\n\020is_solution_find\030\001 \002(\010\022=\n\rsoluti" +
      "on_list\030\002 \003(\0132&.com.errclipse.rmi.interf" +
      "aces.SolutionB\024B\022GGeneralErrorClazz"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_errclipse_rmi_interfaces_ErrorQuery_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_errclipse_rmi_interfaces_ErrorQuery_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_errclipse_rmi_interfaces_ErrorQuery_descriptor,
              new java.lang.String[] { "LanguageName", "LibraryName", "MethodName", "ErrorName", },
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery.class,
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.ErrorQuery.Builder.class);
          internal_static_com_errclipse_rmi_interfaces_Solution_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_errclipse_rmi_interfaces_Solution_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_errclipse_rmi_interfaces_Solution_descriptor,
              new java.lang.String[] { "Decs", "LocalScore", "GlobalScore", },
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.class,
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.Solution.Builder.class);
          internal_static_com_errclipse_rmi_interfaces_SolutionResultList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_errclipse_rmi_interfaces_SolutionResultList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_errclipse_rmi_interfaces_SolutionResultList_descriptor,
              new java.lang.String[] { "IsSolutionFind", "SolutionList", },
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList.class,
              com.errclipse.rmi.interfaces.GGeneralErrorClazz.SolutionResultList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
