// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errorReturn.proto

package com.errclipse.rmi.interfaces;

public final class urlList {
  private urlList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface errorRelationUrlsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 errorId = 1;
    boolean hasErrorId();
    int getErrorId();
    
    // repeated string urls = 2;
    java.util.List<String> getUrlsList();
    int getUrlsCount();
    String getUrls(int index);
  }
  public static final class errorRelationUrls extends
      com.google.protobuf.GeneratedMessage
      implements errorRelationUrlsOrBuilder {
    // Use errorRelationUrls.newBuilder() to construct.
    private errorRelationUrls(Builder builder) {
      super(builder);
    }
    private errorRelationUrls(boolean noInit) {}
    
    private static final errorRelationUrls defaultInstance;
    public static errorRelationUrls getDefaultInstance() {
      return defaultInstance;
    }
    
    public errorRelationUrls getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.errclipse.rmi.interfaces.urlList.internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.errclipse.rmi.interfaces.urlList.internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 errorId = 1;
    public static final int ERRORID_FIELD_NUMBER = 1;
    private int errorId_;
    public boolean hasErrorId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrorId() {
      return errorId_;
    }
    
    // repeated string urls = 2;
    public static final int URLS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList urls_;
    public java.util.List<String>
        getUrlsList() {
      return urls_;
    }
    public int getUrlsCount() {
      return urls_.size();
    }
    public String getUrls(int index) {
      return urls_.get(index);
    }
    
    private void initFields() {
      errorId_ = 0;
      urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasErrorId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorId_);
      }
      for (int i = 0; i < urls_.size(); i++) {
        output.writeBytes(2, urls_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < urls_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(urls_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUrlsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.errclipse.rmi.interfaces.urlList.errorRelationUrls parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.errclipse.rmi.interfaces.urlList.errorRelationUrls prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.errclipse.rmi.interfaces.urlList.errorRelationUrlsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.errclipse.rmi.interfaces.urlList.internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.errclipse.rmi.interfaces.urlList.internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_fieldAccessorTable;
      }
      
      // Construct using com.errclipse.rmi.interfaces.urlList.errorRelationUrls.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.errclipse.rmi.interfaces.urlList.errorRelationUrls.getDescriptor();
      }
      
      public com.errclipse.rmi.interfaces.urlList.errorRelationUrls getDefaultInstanceForType() {
        return com.errclipse.rmi.interfaces.urlList.errorRelationUrls.getDefaultInstance();
      }
      
      public com.errclipse.rmi.interfaces.urlList.errorRelationUrls build() {
        com.errclipse.rmi.interfaces.urlList.errorRelationUrls result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.errclipse.rmi.interfaces.urlList.errorRelationUrls buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.errclipse.rmi.interfaces.urlList.errorRelationUrls result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.errclipse.rmi.interfaces.urlList.errorRelationUrls buildPartial() {
        com.errclipse.rmi.interfaces.urlList.errorRelationUrls result = new com.errclipse.rmi.interfaces.urlList.errorRelationUrls(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorId_ = errorId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          urls_ = new com.google.protobuf.UnmodifiableLazyStringList(
              urls_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.urls_ = urls_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.errclipse.rmi.interfaces.urlList.errorRelationUrls) {
          return mergeFrom((com.errclipse.rmi.interfaces.urlList.errorRelationUrls)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.errclipse.rmi.interfaces.urlList.errorRelationUrls other) {
        if (other == com.errclipse.rmi.interfaces.urlList.errorRelationUrls.getDefaultInstance()) return this;
        if (other.hasErrorId()) {
          setErrorId(other.getErrorId());
        }
        if (!other.urls_.isEmpty()) {
          if (urls_.isEmpty()) {
            urls_ = other.urls_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUrlsIsMutable();
            urls_.addAll(other.urls_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasErrorId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorId_ = input.readInt32();
              break;
            }
            case 18: {
              ensureUrlsIsMutable();
              urls_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 errorId = 1;
      private int errorId_ ;
      public boolean hasErrorId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrorId() {
        return errorId_;
      }
      public Builder setErrorId(int value) {
        bitField0_ |= 0x00000001;
        errorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string urls = 2;
      private com.google.protobuf.LazyStringList urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUrlsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          urls_ = new com.google.protobuf.LazyStringArrayList(urls_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getUrlsList() {
        return java.util.Collections.unmodifiableList(urls_);
      }
      public int getUrlsCount() {
        return urls_.size();
      }
      public String getUrls(int index) {
        return urls_.get(index);
      }
      public Builder setUrls(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addUrls(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllUrls(
          java.lang.Iterable<String> values) {
        ensureUrlsIsMutable();
        super.addAll(values, urls_);
        onChanged();
        return this;
      }
      public Builder clearUrls() {
        urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addUrls(com.google.protobuf.ByteString value) {
        ensureUrlsIsMutable();
        urls_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.errclipse.rmi.interfaces.errorRelationUrls)
    }
    
    static {
      defaultInstance = new errorRelationUrls(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.errclipse.rmi.interfaces.errorRelationUrls)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021errorReturn.proto\022\034com.errclipse.rmi.i" +
      "nterfaces\"2\n\021errorRelationUrls\022\017\n\007errorI" +
      "d\030\001 \002(\005\022\014\n\004urls\030\002 \003(\tB\tB\007urlList"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_errclipse_rmi_interfaces_errorRelationUrls_descriptor,
              new java.lang.String[] { "ErrorId", "Urls", },
              com.errclipse.rmi.interfaces.urlList.errorRelationUrls.class,
              com.errclipse.rmi.interfaces.urlList.errorRelationUrls.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
